### ISSUE TITLE
Error while seeding : Connection refused - connect(2) for "centos7-devel.example.com" port 8443

### ISSUE THREAD

**Issue by swapnilabnave** [Katello/forklift#298]
* Error backtrace(partial):
```
rake aborted!
There was an issue with the backend service candlepin: Connection refused - connect(2) for "centos7-devel.example.com" port 8443
/home/vagrant/katello/app/lib/actions/middleware/backend_services_check.rb:17:in `block in plan'
/home/vagrant/katello/app/lib/actions/middleware/backend_services_check.rb:15:in `each'
/home/vagrant/katello/app/lib/actions/middleware/backend_services_check.rb:15:in `plan'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:22:in `call'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:26:in `pass'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware.rb:17:in `pass'
/home/vagrant/katello/app/lib/actions/middleware/propagate_candlepin_errors.rb:5:in `block in plan'
/home/vagrant/katello/app/lib/actions/middleware/propagate_candlepin_errors.rb:19:in `propagate_candlepin_errors'
/home/vagrant/katello/app/lib/actions/middleware/propagate_candlepin_errors.rb:5:in `plan'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:22:in `call'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:26:in `pass'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware.rb:17:in `pass'
/home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:9:in `plan'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:22:in `call'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:26:in `pass'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware.rb:17:in `pass'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware.rb:34:in `plan'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:22:in `call'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware/stack.rb:26:in `pass'
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.15/lib/dynflow/middleware.rb:17:in `pass'
/home/vagrant/katello/app/lib/actions/middleware/keep_locale.rb:7:in `plan'
```

* Steps followed:

```
$ vagrant up centos7-devel
$ vagrant ssh centos7-devel

# bundle install --without=mysql2
# rake db:migrate
# rake db:seed SEED_ORGANIZATION="Default Organization" SEED_LOCATION="Default Location" SEED_ADMIN_PASSWORD="admin"
```

I had previously setup centos7-devel multiple times but didn't faced any such issue. This is the first instance I am seeing errors with `rake db:seed`

--

What different I might have done is boxes.yaml

```yaml
centos7-devel:
  box: centos7
  shell: 'yum -y install ruby && cd /vagrant && ./setup.rb'
  options: --scenario=katello-devel
  installer: --katello-devel-github-username swapnilabnave --katello-devel-upstream-remote-name origin --katello-devel-extra-plugins theforeman/foreman_remote_execution --katello-devel-extra-plugins theforeman/foreman_discovery
  disk_size: 105
```

This time I had specified extensions in installer: `foreman_remote_execution` and `foreman_discovery`

Before this I used to omit the extensions part and setup would complete without any noise.

--

[Complete error backtrace](https://gist.github.com/swapnilabnave/4cb57f13aa8a5e8e7e55b2e22587db9c)
